package com.upc.gessi.qrapids.app.domain.models;

public enum AlertType {
    CATEGORY_DOWNGRADE,
    TRESPASSED_THRESHOLD,
    ALERT_NOT_TREATED,
    CATEGORY_UPGRADE,
    PREDICTED_CATEGORY_DOWNGRADE,
    PREDICTED_CATEGORY_UPGRADE,
    PREDICTED_TRESPASSED_THRESHOLD
}
